language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: true
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SQLAlchemy"); Pkg.test("SQLAlchemy");'
addons:
  apt:
    packages:
      - sqlite3
      - python2.7-dev

