language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SQLAlchemy"); Pkg.test("SQLAlchemy");'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sqlite3 python-sqlalchemy -qq
sudo: required

